# https://taskfile.dev

version: '2'

silent: true

tasks:

  build:
    cmds:
      - docker build -t headless-deployment .

  rebuild:
    cmds:
      - docker build --no-cache -t headless-deployment .

  start:
    cmds:
      - docker run --rm -d --net=host --cap-add=NET_ADMIN -e SUBNET=192.168.1.0 -e USERNAME=enforge -v $PWD/netboot:/netboot -v $PWD/hosts:/hosts --name headless-deployment headless-deployment

  reinstall-host:
    cmds:
      - |
        read -p "Please enter the host you want to reboot from network: " host
        read -p "Please enter the user you want to be: [enforge] " user
        user=${user:=enforge}  # if variable not set or null, set it to default

        read -p "Are you SURE, you don't need to just run a reboot? [y|n] " -n 1 -r
        echo # to move cursor to next line
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
          ssh -t -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -o "LogLevel=error" "$user@$host" 'sudo efibootmgr -A -b $(efibootmgr | grep "^Boot....\* debian$" | cut -c5-8) && sudo systemctl reboot'
        fi
        echo # start new line
