# https://taskfile.dev

version: '2'

silent: true

tasks:

  build:
    cmds:
      - docker build -t headless-deployment .

  rebuild:
    cmds:
      - docker build --no-cache -t headless-deployment .

  start:
    cmds:
      - docker run --rm -d --net=host --cap-add=NET_ADMIN -e SUBNET=192.168.1.0 -e USERNAME=enforge -v $PWD/netboot:/netboot -v $PWD/hosts:/hosts --name headless-deployment headless-deployment
